name: Develop

on:
  push:
    branches: [ "develop" ]
    
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install Prerequisites
      run: sudo apt-get install -y build-essential gcc-aarch64-linux-gnu binutils-aarch64-linux-gnu

    - name: Make All
      run: make all