name: Main

on:
  push:
    branches: [ "main" ]
    
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Prerequisites
      run: sudo apt-get install -y build-essential gcc-aarch64-linux-gnu binutils-aarch64-linux-gnu

    - name: Make Package
      run: make package